### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by TwistedModding** [alandtse/hdtSMP64#10]
[Crash_2022_10_10_17-37-8.txt](https://github.com/alandtse/hdtSMP64/files/9749642/Crash_2022_10_10_17-37-8.txt)
[Crash_2022_10_10_17-40-53.txt](https://github.com/alandtse/hdtSMP64/files/9749643/Crash_2022_10_10_17-40-53.txt)

Getting these crashes while just walking around in third person, then stopping and moving my camera. Thats how exactly what i did right before it crashed both times

**Comment by alandtse** [comment]
Oh thanks. Please use [Crashlogger](https://www.nexusmods.com/skyrimspecialedition/mods/59818) so we can actually get PDB information from the crash. Please also use the latest release in the [releases ](https://github.com/alandtse/hdtSMP64/releases/tag/2022-10-20)

**Comment by TwistedModding** [comment]
Seems to be fixed on latest version, although I can't extensively test just now because I have to figure out why im freezing. I'll reopen if it turns out to not be fixed.
